[package]
authors = ["Pierre Guilleminot <pierre.guilleminot@gmail.com>"]
name = "musique"
version = "0.1.0"

[dependencies]
webrender = { git = "https://github.com/servo/webrender" }
gleam = "0.4.8"
# glutin = "0.9.2"
servo-glutin = "0.11.1"
